### ISSUE TITLE
Checklist CRAN submit 0.6.0

### ISSUE THREAD

**Issue by hannes** [hannesmuehleisen/MonetDBLite-R#24]
Candidate revision: https://github.com/hannesmuehleisen/MonetDBLite-R/tree/v0.6.0-6

- [x] [CRAN check issues](https://cran.r-project.org/web/checks/check_results_MonetDBLite.html) fixed (look at all files)
- [x] [Travis](https://travis-ci.org/hannesmuehleisen/MonetDBLite-R) green
- [x] [AppVeyor](https://ci.appveyor.com/project/hannesmuehleisen/MonetDBLite-R) green
- [ ]  R CMD check --as-cran using R-devel and leak checks (rocks080)
- [ ]  R CMD check with -Wall with GCC 8 (VM)
- [ ] R CMD check --as-cran  --use-valgrind (rocks080)
- [x] [Winbuilder](https://win-builder.r-project.org/) no warnings
- [x] R-hub happy
- [x] [Sisyphus](https://sisyphus.project.cwi.nl) Linux green
- [x] [Sisyphus](https://sisyphus.project.cwi.nl) Windows green

**Comment by hannesmuehleisen** [comment]
Travis: https://travis-ci.org/hannesmuehleisen/MonetDBLite-R/builds/399066068
Appveyor: https://ci.appveyor.com/project/hannesmuehleisen/monetdblite-r/build/1.0.166

**Comment by hannesmuehleisen** [comment]
R-Hub: 

 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-e9c601ae9a1748d79c52dcd7dd19fe06
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-e6c9cf3ccc704b7a86f55db5649095dd
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-54c34b5f6d6448cbb50c516a83b900b1
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-cca7e737113f4f578c8030db4f9f0c7c
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-015f0f3fbd074eb58807214270c18305
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-c5bb6e6510b542cdbe34291f7d8fec8a
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-7ca29f968732411a863a90b24b1f8c22
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-ca9a08c69f714df7a05ec4b624ff5f19
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-937c638f95584c2ca533fb342268d5b3
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-78b36d9740b44f6fa3b0ddc43e490a54
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-678121bedbda4013a23a8e8d3b34e4ca
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-669451a01f56444bb4f2f30c6a6860bc
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-309337bceed3417caa468f70946537fc
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-d26665029dd14bd7815b188c74d2a7a6
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-b9dee77e2cb442a4b28d2b5b2145beb7
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-f5240f7cc9a64f7bb098a8ff64f65085
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-3d9975667ed84d15b82c72bd8d485dc6
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-64bec1885f6e4e9f93a199e6929c35cb

**Comment by hannesmuehleisen** [comment]
rchk sez
````

ERROR: too many states (abstraction error?) in function RunGenCollect

Function bat_to_sexp
  [PB] has too high protection stack depth results will be incomplete
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [PB] has an unsupported form of unprotect (not constant, not variable), results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/converters.c.h:293
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/converters.c.h:293
  [PB] has possible protection stack imbalance /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/converters.c.h:412

Function monetdb_query_R
  [UP] unprotected variable names while calling allocating function BATdescriptor.8027 /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:144
  [UP] unprotected variable retlist while calling allocating function BATdescriptor.8027 /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:144
  [UP] unprotected variable names while calling allocating function Rf_mkCharCE /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:146
  [UP] unprotected variable retlist while calling allocating function Rf_mkCharCE /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:146
  [PB] has an unsupported form of unprotect (not constant, not variable), results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:149
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:149
  [UP] unprotected variable names while calling allocating function bat_to_sexp /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:158
  [UP] unprotected variable retlist while calling allocating function bat_to_sexp /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:158
  [PB] has an unsupported form of unprotect (not constant, not variable), results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:159
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:159
  [UP] unprotected variable names while calling allocating function BBPunfix /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:166
  [PB] has negative depth /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:168
  [UP] attempt to unprotect more items (2) than protected (1), results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:168
  [UP] unprotected variable names while calling allocating function Rf_ScalarReal /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:170
  [UP] unprotected variable names while calling allocating function Rf_install /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:170
  [UP] unprotected variable names while calling allocating function Rf_setAttrib(V,S:__rows,V) /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:170
  [UP] unprotected variable retlist while calling allocating function Rf_ScalarReal /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:170
  [UP] unprotected variable retlist while calling allocating function Rf_install /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:170
  [UP] unprotected variable names while calling allocating function Rf_ScalarReal /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:173
  [UP] unprotected variable names while calling allocating function Rf_install /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:173
  [UP] unprotected variable names while calling allocating function Rf_setAttrib(V,S:__prepare,V) /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:173
  [UP] unprotected variable retlist while calling allocating function Rf_ScalarReal /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:173
  [UP] unprotected variable retlist while calling allocating function Rf_install /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:173
  [UP] unprotected variable names while calling allocating function monetdb_cleanup_result /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:177
  [UP] unprotected variable retlist while calling allocating function monetdb_cleanup_result /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:177
  [UP] unprotected variable retlist while calling allocating function PutRNGstate /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:179
  [PB] has negative depth /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:180
  [UP] attempt to unprotect more items (2) than protected (0), results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:180
  [UP] attempt to unprotect more items (2) than protected (1), results will be incomplete /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:180
  [PB] has possible protection stack imbalance /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/embeddedr.c:188

Function monetdb_r_dressup
  [PB] has possible protection stack imbalance /opt/R-svn/packages/build/JuL9IFqP/MonetDBLite/src/embeddedr/converters.c.h:152
Analyzed 5305 functions, traversed 264608 states.
````

**Comment by hannesmuehleisen** [comment]
restarting because merged PR

**Comment by hannesmuehleisen** [comment]
R-Hub
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-5d2fd54cb8bb41eab8355b29989fb797
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-edc563a0326446b7b6fd2dbd3d73d1e6
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-0306d4e4272f4e179847699ba7fbe605
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-5edf05aad0854ff2981af4f8a2947f29
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-54565cc41d8b4c699795b59926c1c0c5
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-5aeceaf665b0443bb0442c5306cd3483
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-be3c4d7123aa4434a86de9e8ce94f3ce
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-0da53a0508cc4d369855ac8b3401d82e
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-aec47b36bd0c463391ac9f178d0199ad
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-5b81f8578467491ca7984c3e10837aab
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-1174f59e1ca6483497b461c601451717
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-ee2b5c7f8c9e488db931b2ba720cd920
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-9ad8aa2906f642e7a2a48c24bff0cbae
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-f73cf9f50681473fa2e792d09aec722b
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-cd061d5035ec4862b8e63697baa80142
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-c0dee97223704bccafb0c935dcfedfed
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-ad31e3533287481cbc82d6c25fce5de5
 - http://builder.r-hub.io/status/MonetDBLite_0.6.0.tar.gz-a28e4a4f8233449eba1df3625a57e111

**Comment by hannesmuehleisen** [comment]
https://win-builder.r-project.org/U1Xj5dj7AoAa/

**Comment by hannesmuehleisen** [comment]
Submitted
